# Generated by Django 5.2.16 on 2026-08-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Client request ID'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Title'),
        ),
    ]
