# Generated by Django 5.2.16 on 2026-07-13 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='The full text of the terms and conditions.', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Terms and conditions',
                'verbose_name_plural': 'Terms and conditions',
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='VoiceGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('market_file', models.FileField(blank=True, null=True, upload_to='guide/', verbose_name='Market file')),
                ('product_file', models.FileField(blank=True, null=True, upload_to='product/', verbose_name='Product file')),
            ],
            options={
                'verbose_name': 'Voice guide',
                'verbose_name_plural': 'Voice guide',
                'db_table': 'voice_guide',
            },
        ),
    ]
