# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.productkeyword', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='productrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrevision',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='product.product'),
        ),
        migrations.AddField(
            model_name='productrevision',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productshipping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.producttheme', verbose_name='Theme'),
        ),
        migrations.AddIndex(
            model_name='productrevision',
            index=models.Index(fields=['product', 'status'], name='product_revision_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['market', 'status'], name='idx_product_market_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category', 'status'], name='idx_product_category_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_at'], name='idx_product_status_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['market', 'created_at'], name='idx_product_market_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tag'], name='idx_product_tag'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_marketer'], name='idx_product_marketer'),
        ),
    ]
