# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('invoice_number', models.CharField(max_length=10, verbose_name='Invoice number')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=20, verbose_name='Status')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference number')),
                ('track_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference number')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'db_table': 'gateway',
            },
        ),
    ]
