# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('client_request_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Client request ID')),
                ('users', models.JSONField(blank=True, default=list, verbose_name='Users')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='top_left', max_length=20, verbose_name='Position')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiry')),
                ('limitation', models.PositiveSmallIntegerField(default=1000, help_text='Number of allowed uses', verbose_name='Limitation')),
                ('consumed', models.PositiveSmallIntegerField(default=0, help_text='Number of uses', verbose_name='Consumed')),
                ('reserved', models.PositiveSmallIntegerField(default=0, verbose_name='Reserved uses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['product', 'market']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discount',
            },
        ),
    ]
