# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='product/image/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Product keyword',
                'verbose_name_plural': 'Product keywords',
                'db_table': 'product_keyword',
            },
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Product theme',
                'verbose_name_plural': 'Product themes',
                'db_table': 'product_theme',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('good', 'Good'), ('service', 'Service')], max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('technical_detail', models.TextField(blank=True, null=True, verbose_name='Technical detail')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('main_price', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Main price')),
                ('colleague_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Colleague price')),
                ('marketer_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Marketer price')),
                ('maximum_sell_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Maximum sell price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queue', 'In Queue for Publication'), ('not_published', 'Not Published'), ('published', 'Published'), ('needs_editing', 'Needs Editing'), ('inactive', 'Inactive')], default='draft', max_length=20, verbose_name='Status')),
                ('is_marketer', models.BooleanField(default=False, verbose_name='Is marketer')),
                ('is_requirement', models.BooleanField(default=False, verbose_name='Is requirement')),
                ('tag', models.CharField(choices=[('new', 'New'), ('special_offer', 'Special Offer'), ('coming_soon', 'Coming Soon'), ('none', 'None')], default='none', max_length=20, verbose_name='Tag')),
                ('tag_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='top_left', max_length=20, verbose_name='Tag Position')),
                ('sell_type', models.CharField(choices=[('online', 'Online'), ('person', 'Person'), ('both', 'Both')], default='online', max_length=10, verbose_name='Sell type')),
                ('ship_cost_pay_type', models.CharField(choices=[('market', 'Market'), ('customer', 'Customer'), ('free', 'Free')], max_length=10, verbose_name='Ship cost pay type')),
                ('theme_index', models.CharField(blank=True, max_length=2, null=True, verbose_name='Theme Index')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_products', to='product.product', verbose_name='Gift product')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.market', verbose_name='Market')),
                ('required_product', models.ForeignKey(blank=True, help_text='Another product that is required for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_products', to='product.product', verbose_name='Required product')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='top_left', max_length=20, verbose_name='Position')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Percentage')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product discount',
                'verbose_name_plural': 'Product discounts',
                'db_table': 'product_discount',
            },
        ),
    ]
