# Generated by Django 5.2.17 on 2026-08-26 21:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('market', '0009_alter_marketslider_url_marketshippingmethod'),
        ('product', '0003_product_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_bookmark',
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_like',
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'product_report',
            },
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='consumed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('timed', 'Timed'), ('group', 'Group')], default='percent', max_length=12),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='limitation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='reserved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='client_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ship_cost_pay_type',
            field=models.CharField(choices=[('market', 'Market'), ('customer', 'Customer'), ('free', 'Free'), ('none', 'No shipping'), ('store', 'Use store shipping methods')], max_length=10, verbose_name='Ship cost pay type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.producttheme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='percentage',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_discounts', to='product.product', verbose_name='Product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('theme__isnull', False), ('theme_index__isnull', False)), fields=('theme', 'theme_index'), name='uniq_product_theme_slot'),
        ),
        migrations.AddField(
            model_name='productbookmark',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='product.product'),
        ),
        migrations.AddField(
            model_name='productbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='product.product'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='product.product'),
        ),
        migrations.AddConstraint(
            model_name='productbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_product_bookmark_user_product'),
        ),
        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_product_like_user_product'),
        ),
    ]
