# Generated by Django 5.2.17 on 2026-08-20 20:28

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Status')),
                ('owner_description', models.TextField(blank=True, null=True, verbose_name='Owner Descriptions')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('discount_code_snapshot', models.CharField(blank=True, default='', max_length=16)),
                ('discount_percentage_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('subtotal_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('payable_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('inventory_status', models.CharField(choices=[('none', 'Not reserved'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='none', max_length=10)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'db_table': 'order_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
