# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='product/affiliate/image/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Affiliate Product image',
                'verbose_name_plural': 'Affiliate Product images',
                'db_table': 'affiliate_product_image',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProductTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Affiliate Product theme',
                'verbose_name_plural': 'Affiliate Product themes',
                'db_table': 'affiliate_product_theme',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('technical_detail', models.TextField(blank=True, null=True, verbose_name='Technical detail')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('price', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Main price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queue', 'In Queue for Publication'), ('not_published', 'Not Published'), ('published', 'Published'), ('needs_editing', 'Needs Editing'), ('inactive', 'Inactive')], default='draft', max_length=20, verbose_name='Status')),
                ('is_requirement', models.BooleanField(default=False, verbose_name='Is requirement')),
                ('tag', models.CharField(choices=[('new', 'New'), ('special_offer', 'Special Offer'), ('coming_soon', 'Coming Soon'), ('none', 'None')], default='none', max_length=20, verbose_name='Tag')),
                ('tag_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='top_left', max_length=20, verbose_name='Tag Position')),
                ('sell_type', models.CharField(choices=[('online', 'Online'), ('person', 'Person'), ('both', 'Both')], default='online', max_length=10, verbose_name='Sell type')),
                ('ship_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Ship cost')),
                ('ship_cost_pay_type', models.CharField(choices=[('market', 'Market'), ('customer', 'Customer'), ('free', 'Free')], max_length=10, verbose_name='Ship cost pay type')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_affiliate_products', to='affiliate.affiliateproduct', verbose_name='Gift product')),
            ],
            options={
                'verbose_name': 'Affiliate Product',
                'verbose_name_plural': 'Affiliate Products',
                'db_table': 'affiliate_product',
            },
        ),
    ]
