# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('category', '0001_initial'),
        ('market', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='affiliate_products', to='product.productkeyword', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_products', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='required_product',
            field=models.ForeignKey(blank=True, help_text='Another product that is required for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_affiliate_products', to='affiliate.affiliateproduct', verbose_name='Required product'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='affiliateproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='affiliate.affiliateproduct', verbose_name='Affiliate Product'),
        ),
        migrations.AddField(
            model_name='affiliateproducttheme',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_products', to='affiliate.affiliateproducttheme', verbose_name='Theme'),
        ),
    ]
