# Generated by Django 5.2.17 on 2026-08-31 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_initial'),
        ('cart', '0005_order_delivered_at_order_fulfillment_status_and_more'),
        ('category', '0001_initial'),
        ('market', '0006_market_sales_channel'),
        ('product', '0006_product_theme_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField()),
                ('customer_total', models.DecimalField(decimal_places=3, max_digits=14)),
                ('seller_total', models.DecimalField(decimal_places=3, max_digits=14)),
                ('gross_commission', models.DecimalField(decimal_places=3, max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('marketer_total', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('held', 'Held'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='held', max_length=12)),
                ('available_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=12)),
                ('tracking_code', models.CharField(blank=True, default='', max_length=100)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='affiliateproduct',
            constraint=models.UniqueConstraint(fields=('market', 'product'), name='unique_affiliate_product_per_market'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='affiliate_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliate.affiliateproduct'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='cart.order'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commission', to='cart.orderitem'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='commissions',
            field=models.ManyToManyField(blank=True, related_name='payouts', to='affiliate.affiliatecommission'),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['marketer', 'status'], name='affiliate_earning_status_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['seller', 'status'], name='affiliate_sale_status_idx'),
        ),
    ]
