# Generated by Django 5.2.17 on 2026-08-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_affiliatecommission_affiliatepayout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='seller_available_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='seller_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='seller_status',
            field=models.CharField(choices=[('held', 'Held'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='held', max_length=12),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='role',
            field=models.CharField(choices=[('marketer', 'Marketer'), ('seller', 'Seller')], default='marketer', max_length=10),
        ),
    ]
