# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_initial'),
        ('payment', '0002_initial'),
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinvitelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_invite_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketinvitelink',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='market.market'),
        ),
        migrations.AddField(
            model_name='referral',
            name='invite_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referral.marketinvitelink'),
        ),
        migrations.AddField(
            model_name='referral',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Referred By'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL, verbose_name='Referred User'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions', to='market.market'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_referral_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupinviteintent',
            name='invite_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_intents', to='referral.marketinvitelink'),
        ),
        migrations.AddField(
            model_name='signupinviteintent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_invite_intent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeaccess',
            name='invite_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_accesses', to='referral.marketinvitelink'),
        ),
        migrations.AddField(
            model_name='storeaccess',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accesses', to='market.market'),
        ),
        migrations.AddField(
            model_name='storeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='marketinvitelink',
            index=models.Index(fields=['market', 'is_active'], name='invite_market_active_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['beneficiary', 'status'], name='commission_beneficiary_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.UniqueConstraint(fields=('payment', 'beneficiary', 'level'), name='unique_payment_referral_commission'),
        ),
        migrations.AddIndex(
            model_name='storeaccess',
            index=models.Index(fields=['user', 'is_active'], name='store_access_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeaccess',
            constraint=models.UniqueConstraint(fields=('user', 'market'), name='unique_user_store_access'),
        ),
    ]
