# Generated by Django 5.2.17 on 2026-08-20 20:28

import apps.price_inquiry.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('good', 'Good'), ('service', 'Service')], max_length=16, verbose_name='Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('technical_detail', models.TextField(blank=True, null=True, verbose_name='Technical Detail')),
                ('amount', models.CharField(blank=True, max_length=10, null=True, verbose_name='Amount')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit')),
                ('expiry', models.DateTimeField(verbose_name='Expiry')),
                ('send', models.CharField(blank=True, choices=[('sms', 'Sms'), ('chat', 'Chat')], default=None, max_length=5, null=True, verbose_name='Send')),
            ],
            options={
                'verbose_name': 'Price Inquiry',
                'verbose_name_plural': 'Price Inquiries',
                'db_table': 'inquiry',
                'ordering': ['-created_at', 'expiry'],
            },
        ),
        migrations.CreateModel(
            name='InquiryAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('total', models.CharField(max_length=15, verbose_name='Total Price')),
                ('fee', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fee')),
            ],
            options={
                'verbose_name': 'Inquiry Answer',
                'verbose_name_plural': 'Inquiry Answers',
                'db_table': 'inquiry_answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryAnswerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=apps.price_inquiry.models.upload_inquiry_answer_image)),
            ],
            options={
                'verbose_name': 'Inquiry Answer Image',
                'verbose_name_plural': 'Inquiry Answer Images',
                'db_table': 'inquiry_answer_image',
            },
        ),
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=apps.price_inquiry.models.upload_inquiry_image)),
            ],
            options={
                'verbose_name': 'Inquiry Image',
                'verbose_name_plural': 'Inquiry Images',
                'db_table': 'inquiry_image',
            },
        ),
    ]
