# Generated by Django 5.2.17 on 2026-08-31 17:52

import apps.reserve.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def populate_appointment_compatibility(apps, schema_editor):
    Reservation = apps.get_model('reserve', 'Reservation')
    Specialist = apps.get_model('reserve', 'Specialist')
    DayOff = apps.get_model('reserve', 'DayOff')

    for reservation in Reservation.objects.select_related('reserve__service').all():
        reservation.tracking_code = f"AS-{uuid.uuid4().hex[:10].upper()}"
        if reservation.reserve_id:
            reservation.service_id = reservation.reserve.service_id
            reservation.service_name_snapshot = reservation.reserve.service.name
        reservation.status = 'confirmed'
        reservation.confirmed_at = reservation.created_at
        reservation.save(update_fields=(
            'tracking_code', 'service', 'service_name_snapshot', 'status', 'confirmed_at',
        ))

    for specialist in Specialist.objects.prefetch_related('services').all():
        service = specialist.services.order_by('created_at').first()
        if service is not None:
            specialist.market_id = service.market_id
            specialist.save(update_fields=('market',))

    duplicates = set()
    for item in DayOff.objects.order_by('created_at').values('id', 'market_id', 'date'):
        key = (item['market_id'], item['date'])
        if key in duplicates:
            DayOff.objects.filter(id=item['id']).delete()
        else:
            duplicates.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketmembership_admin_approved_at_and_more'),
        ('product', '0006_product_theme_integrity'),
        ('reserve', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('date', models.DateField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'ordering': ('date', 'start'),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount_due',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_mode_snapshot',
            field=models.CharField(blank=True, default='free', max_length=24),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reserve.service'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('held', 'Held for payment'), ('pending_confirmation', 'Pending owner confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('expired', 'Expired')], default='held', max_length=24),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_minutes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='Buffer between appointments in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacity per slot'),
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(720)], verbose_name='Appointment duration in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_advance_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_mode',
            field=models.CharField(choices=[('free', 'Free reservation'), ('fixed', 'Fixed reservation fee'), ('deposit_percent', 'Deposit percentage'), ('full', 'Full service price')], default='free', max_length=24),
        ),
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_service', to='product.product', verbose_name='Service product'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_owner_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialist',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_specialists', to='market.market'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reserve.reservetime', verbose_name='ReservedService'),
        ),
        migrations.RunPython(
            populate_appointment_compatibility,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(default=apps.reserve.models.reservation_tracking_code, editable=False, max_length=16, unique=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['specialist', 'scheduled_start'], name='idx_res_spec_start'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'hold_expires_at'], name='idx_res_status_expiry'),
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(fields=('market', 'date'), name='uniq_market_day_off'),
        ),
        migrations.AddField(
            model_name='specialisttimeoff',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='reserve.specialist'),
        ),
        migrations.AddConstraint(
            model_name='specialisttimeoff',
            constraint=models.UniqueConstraint(fields=('specialist', 'date', 'start', 'end'), name='uniq_specialist_time_off'),
        ),
    ]
