# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertise', '0001_initial'),
        ('product', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertises', to='region.province', verbose_name='State'),
        ),
    ]
