# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertise', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertises', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='advimage',
            name='advertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertise.advertisement', verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='advertise.advkeyword', verbose_name='Keywords'),
        ),
    ]
