# Generated by Django 5.2.17 on 2026-08-28 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketshippingmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmembership',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_market_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_market_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='owner_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketmembership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('phone_verified', 'Phone verified'), ('profile_incomplete', 'Profile incomplete'), ('owner_review', 'Waiting for owner review'), ('admin_review', 'Waiting for admin review'), ('active', 'Active'), ('needs_editing', 'Needs editing'), ('rejected', 'Rejected'), ('owner_disabled', 'Disabled by owner')], default='active', max_length=24),
        ),
    ]
