# Generated by Django 5.2.17 on 2026-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketmembership_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='sales_channel',
            field=models.CharField(choices=[('seller', 'Seller'), ('affiliate', 'Affiliate marketer')], db_index=True, default='seller', max_length=12, verbose_name='Sales channel'),
        ),
    ]
