# Generated by Django 5.2.16 on 2026-07-13 16:49

import apps.chat.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Total Messages')),
                ('messages_today', models.PositiveIntegerField(default=0, verbose_name='Messages Today')),
                ('messages_this_week', models.PositiveIntegerField(default=0, verbose_name='Messages This Week')),
                ('messages_this_month', models.PositiveIntegerField(default=0, verbose_name='Messages This Month')),
                ('active_participants', models.PositiveIntegerField(default=0, verbose_name='Active Participants')),
                ('new_participants_today', models.PositiveIntegerField(default=0, verbose_name='New Participants Today')),
                ('avg_response_time_minutes', models.FloatField(default=0, verbose_name='Average Response Time (minutes)')),
                ('files_shared', models.PositiveIntegerField(default=0, verbose_name='Files Shared')),
                ('total_file_size', models.PositiveBigIntegerField(default=0, verbose_name='Total File Size (bytes)')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='Last Calculated At')),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'db_table': 'chat_chatanalytics',
            },
        ),
        migrations.CreateModel(
            name='ChatMembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_added', 'Member added'), ('member_removed', 'Member removed'), ('member_left', 'Member left'), ('role_changed', 'Role changed'), ('ownership_transferred', 'Ownership transferred'), ('room_archived', 'Room archived')], max_length=32)),
                ('old_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=10, null=True)),
                ('new_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'chat_membership_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('location', 'Location'), ('system', 'System')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(db_column='text', default='', help_text='Message content', verbose_name='Content')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chat.models.chat_file_upload_path, verbose_name='File Attachment')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='File Type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('encryption_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Encryption Key')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='Failure Reason')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Read At')),
            ],
            options={
                'verbose_name': 'Message Read',
                'verbose_name_plural': 'Messages Read',
                'db_table': 'chat_chatmessageread',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10, verbose_name='Role')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('role_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'db_table': 'chat_conversation_participants',
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Chat Room', help_text='Name of the chat room', max_length=200, null=True, verbose_name='Room Name')),
                ('description', models.TextField(blank=True, help_text='Description of the chat room', null=True, verbose_name='Description')),
                ('room_type', models.CharField(blank=True, choices=[('private', 'Private Chat'), ('group', 'Group Chat'), ('support', 'Support Chat'), ('market', 'Market Chat')], default='private', max_length=20, null=True, verbose_name='Room Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked')], default='active', max_length=20, verbose_name='Status')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether messages in this room are encrypted', verbose_name='Is Encrypted')),
                ('allow_file_sharing', models.BooleanField(default=True, verbose_name='Allow File Sharing')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='Max Participants')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity At')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Ticket Number')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General'), ('complaint', 'Complaint'), ('feature_request', 'Feature Request')], default='general', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer'), ('pending_agent', 'Pending Agent'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Activity At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolution')),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5', null=True, verbose_name='Satisfaction Rating')),
                ('satisfaction_feedback', models.TextField(blank=True, null=True, verbose_name='Satisfaction Feedback')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'chat_supportticket',
                'ordering': ['-opened_at'],
            },
        ),
    ]
