# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zarinpal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('authority', models.CharField(blank=True, max_length=64, null=True, verbose_name='Authority')),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Transaction ID')),
                ('verification_data', models.JSONField(blank=True, null=True, verbose_name='Verification Data')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='Target ID')),
                ('gateway_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_payments', to='contenttypes.contenttype', verbose_name='Gateway Content Type')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_payments', to='contenttypes.contenttype', verbose_name='Target Content Type')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
