# Generated by Django 5.1.15 on 2026-07-13 19:19

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='payment_amount_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='zarinpal',
            constraint=models.UniqueConstraint(condition=models.Q(('authority__isnull', False), models.Q(('authority', ''), _negated=True)), fields=('authority',), name='payment_zarinpal_authority_unique'),
        ),
        migrations.AddConstraint(
            model_name='zarinpal',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id',), name='payment_zarinpal_transaction_unique'),
        ),
    ]
