# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('registration_id', models.CharField(max_length=4096, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notification_device_installation',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('payment_success', 'Payment Success'), ('new_message', 'New Message'), ('market_approved', 'Market Approved'), ('product_published', 'Product Published'), ('discount_available', 'Discount Available'), ('system_maintenance', 'System Maintenance'), ('security_alert', 'Security Alert')], max_length=50, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket')], max_length=20, verbose_name='Channel')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional Data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='Failure Reason')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Attempt Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], max_length=20, verbose_name='Status')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push Notifications Enabled')),
                ('push_orders', models.BooleanField(default=True, verbose_name='Order Notifications')),
                ('push_messages', models.BooleanField(default=True, verbose_name='Message Notifications')),
                ('push_marketing', models.BooleanField(default=True, verbose_name='Marketing Notifications')),
                ('push_system', models.BooleanField(default=True, verbose_name='System Notifications')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications Enabled')),
                ('email_orders', models.BooleanField(default=True, verbose_name='Order Emails')),
                ('email_messages', models.BooleanField(default=False, verbose_name='Message Emails')),
                ('email_marketing', models.BooleanField(default=True, verbose_name='Marketing Emails')),
                ('email_system', models.BooleanField(default=True, verbose_name='System Emails')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Notifications Enabled')),
                ('sms_orders', models.BooleanField(default=True, verbose_name='Order SMS')),
                ('sms_messages', models.BooleanField(default=False, verbose_name='Message SMS')),
                ('sms_marketing', models.BooleanField(default=False, verbose_name='Marketing SMS')),
                ('sms_system', models.BooleanField(default=True, verbose_name='System SMS')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Queue Priority')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled At')),
                ('is_processing', models.BooleanField(default=False, verbose_name='Is Processing')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Started At')),
            ],
            options={
                'verbose_name': 'Notification Queue',
                'verbose_name_plural': 'Notification Queues',
                'ordering': ['-priority', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('payment_success', 'Payment Success'), ('new_message', 'New Message'), ('market_approved', 'Market Approved'), ('product_published', 'Product Published'), ('discount_available', 'Discount Available'), ('system_maintenance', 'System Maintenance'), ('security_alert', 'Security Alert')], max_length=50, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket')], max_length=20, verbose_name='Channel')),
                ('subject', models.CharField(help_text='Subject line for email notifications', max_length=200, verbose_name='Subject')),
                ('title', models.CharField(help_text='Title for push notifications', max_length=200, verbose_name='Title')),
                ('body', models.TextField(help_text='Main content of the notification', verbose_name='Body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available variables for template rendering', verbose_name='Template Variables')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['notification_type', 'channel'],
            },
        ),
    ]
