# Generated by Django 5.2.17 on 2026-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('payment_success', 'Payment Success'), ('new_message', 'New Message'), ('market_approved', 'Market Approved'), ('product_published', 'Product Published'), ('discount_available', 'Discount Available'), ('system_maintenance', 'System Maintenance'), ('security_alert', 'Security Alert'), ('appointment_update', 'Appointment update')], max_length=50, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('payment_success', 'Payment Success'), ('new_message', 'New Message'), ('market_approved', 'Market Approved'), ('product_published', 'Product Published'), ('discount_available', 'Discount Available'), ('system_maintenance', 'System Maintenance'), ('security_alert', 'Security Alert'), ('appointment_update', 'Appointment update')], max_length=50, verbose_name='Notification Type'),
        ),
    ]
