# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mlmodelartifact',
            constraint=models.UniqueConstraint(fields=('model_type', 'version'), name='analytics_unique_model_version'),
        ),
        migrations.AddConstraint(
            model_name='mlmodelartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('model_type',), name='analytics_one_active_model_type'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.usersession'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailymetric',
            index=models.Index(fields=['scope', 'date'], name='analytics_d_scope_33a0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailymetric',
            index=models.Index(fields=['market', 'date'], name='analytics_d_market__6c248d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailymetric',
            index=models.Index(fields=['product', 'date'], name='analytics_d_product_6c5e15_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdailymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('market__isnull', True), ('product__isnull', True), ('scope', 'platform')), fields=('date',), name='analytics_unique_platform_day'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdailymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('market__isnull', False), ('product__isnull', True), ('scope', 'market')), fields=('date', 'market'), name='analytics_unique_market_day'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdailymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('scope', 'product')), fields=('date', 'product'), name='analytics_unique_product_day'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdailymetric',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('market__isnull', True), ('product__isnull', True), ('scope', 'platform')), models.Q(('market__isnull', False), ('product__isnull', True), ('scope', 'market')), models.Q(('product__isnull', False), ('scope', 'product')), _connector='OR'), name='analytics_scope_dimensions_valid'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_u_user_id_132036_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='analytics_u_is_acti_35c242_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='analytics_session_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'occurred_at'], name='analytics_e_user_id_2fcb42_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='analytics_e_event_t_6bfff6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['product', 'event_type', 'occurred_at'], name='analytics_e_product_f52099_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['market', 'event_type', 'occurred_at'], name='analytics_e_market__963896_idx'),
        ),
    ]
