# Generated by Django 5.2.17 on 2026-08-20 20:28

import apps.advertise.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=apps.advertise.models.upload_advertise_image)),
            ],
            options={
                'verbose_name': 'Advertisement Image',
                'verbose_name_plural': 'Advertisement Images',
                'db_table': 'advertisement_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'advertise_keyword',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('service', 'Service'), ('good', 'Good')], max_length=10, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='category.category', verbose_name='Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertises', to='region.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisement',
                'ordering': ['-created_at'],
            },
        ),
    ]
