# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basesmsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulksms',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.line', verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='patternsms',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.template'),
        ),
    ]
