# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('market_fee', models.DecimalField(decimal_places=3, help_text='Fee to be paid by the market owner for this category.', max_digits=14, verbose_name='Market Fee')),
                ('market_slider_img', models.ImageField(blank=True, help_text='This image is not visible to owners.', null=True, upload_to='market/admin/', verbose_name='Market slider image')),
                ('market_slider_url', models.CharField(blank=True, max_length=20, null=True, verbose_name='Market slider url')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'product Groups',
                'db_table': 'product_group',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('market_fee', models.DecimalField(decimal_places=3, help_text='Fee to be paid by the market owner for this category.', max_digits=14, verbose_name='Market Fee')),
                ('market_slider_img', models.ImageField(blank=True, help_text='This image is not visible to owners.', null=True, upload_to='market/admin/', verbose_name='Market slider image')),
                ('market_slider_url', models.CharField(blank=True, max_length=20, null=True, verbose_name='Market slider url')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.productgroup', verbose_name='Product Group')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'product Categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.productcategory', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product Sub Category',
                'verbose_name_plural': 'product sub categories',
                'db_table': 'product_subcategory',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('market_fee', models.DecimalField(decimal_places=3, help_text='Fee to be paid by the market owner for this subcategory.', max_digits=14, verbose_name='Market Fee')),
                ('market_slider_img', models.ImageField(blank=True, help_text='This image is not visible to owners.', null=True, upload_to='market/admin/', verbose_name='Market slider image')),
                ('market_slider_url', models.CharField(blank=True, max_length=20, null=True, verbose_name='Market slider url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'sub_category',
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Sub Category'),
        ),
    ]
