# Generated by Django 5.2.17 on 2026-08-26 21:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('market', '0009_alter_marketslider_url_marketshippingmethod'),
        ('product', '0003_product_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.marketshippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.productdiscount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_discount_percentage_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
