# Generated by Django 5.2.17 on 2026-08-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_shipping_amount_order_shipping_method_and_more'),
        ('market', '0011_market_sales_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], db_index=True, default='unfulfilled', max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='affiliate_gross_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='affiliate_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributed_order_items', to='market.market'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='affiliate_platform_fee_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_settlement_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='source_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_order_items', to='market.market'),
        ),
    ]
