# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_initial'),
        ('reserve', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.reservetime', verbose_name='ReservedService'),
        ),
        migrations.AddField(
            model_name='service',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='reservetime',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_times', to='reserve.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, to='reserve.service', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.specialist', verbose_name='Specialist'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'is_paid'], name='idx_reservation_user_paid'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['specialist', 'created_at'], name='idx_res_spec_created'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reserve', 'created_at'], name='idx_reservation_reserve_date'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['is_paid', 'created_at'], name='idx_reservation_paid_date'),
        ),
    ]
