"""
Django settings for asoud project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

from .logging import LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment with a safe fallback for local/dev only
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Force DEBUG=False in production
if os.environ.get('DJANGO_SETTINGS_MODULE') == 'config.settings.production':
    DEBUG = False

# Allowed hosts from env (comma-separated)
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

# Security: Ensure ALLOWED_HOSTS is not empty in production
# Note: This check is moved to production.py where ALLOWED_HOSTS is properly configured


# Application definition

INSTALLED_APPS = [
    # asgi
    'channels',
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.base',
    'apps.core',
    'apps.category',
    'apps.cart',
    'apps.chat',
    'apps.comment',
    'apps.gateway',
    'apps.information',
    'apps.market',
    'apps.product',
    'apps.region',
    'apps.users',
    'apps.discount',
    'apps.sms',
    'apps.reserve',
    'apps.price_inquiry',
    'apps.notification',
    'apps.flutter',
    'apps.market_subdomain',
    'apps.advertise',
    'apps.affiliate',
    'apps.referral',
    'apps.wallet',
    'apps.payment',
    'apps.analytics',

    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    
    # CORS headers
    'corsheaders',

    # subdomain storefront routing
    'django_hosts',

    # comment system
    'django.contrib.sites',
    'django_comments_xtd',
    'django_comments',
    
    # Monitoring & Metrics
    'django_prometheus',
]

# Custom Authentication User Model
AUTH_USER_MODEL = 'users.User'

# Enhanced Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'config.validators.CustomPasswordValidator',
    },
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Re-enabled CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.database_performance.DatabasePerformanceMiddleware',  # Performance monitoring
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

ROOT_URLCONF = 'config.urls'
ROOT_HOSTCONF = 'config.hosts'
DEFAULT_HOST = 'main'
PARENT_HOST = os.getenv('ASOUD_PARENT_HOST', 'asoud.ir')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

USE_SQLITE = os.environ.get('USE_SQLITE', 'false').lower() == 'true'

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME'),
            'USER': os.environ.get('DATABASE_USERNAME'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
            'HOST': os.environ.get('DATABASE_HOST', 'db'),
            'PORT': str(os.environ.get('DATABASE_PORT', '5432')),
            # Connection pooling for better performance
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
            'OPTIONS': {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000',  # 30 second query timeout
            },
            # Connection pool settings (requires psycopg2)
            'CONN_HEALTH_CHECKS': True,  # Django 4.1+ feature
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Allow override via environment to avoid host-mount permission issues in dev
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, "static"))
# Using default StaticFilesStorage in base; set Manifest in production only.
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unsafe/fabricated analytics remain unreachable until their calculations and
# tenant scoping are repaired and explicitly enabled in a later release.
ANALYTICS_ENABLED = False
SMS_MOCK_SEND = False
OTP_ALLOW_LOCAL_CACHE = False
ASOUD_TOKEN_TTL_SECONDS = int(os.environ.get('ASOUD_TOKEN_TTL_SECONDS', 30 * 24 * 60 * 60))
ASOUD_WS_TICKET_TTL_SECONDS = int(os.environ.get('ASOUD_WS_TICKET_TTL_SECONDS', 60))

# Forwarded client IPs are trusted only when the direct peer is in this list.
# The edge proxy must overwrite X-Real-IP and remove inbound copies.
ASOUD_TRUSTED_PROXY_CIDRS = tuple(
    value.strip()
    for value in os.environ.get('ASOUD_TRUSTED_PROXY_CIDRS', '').split(',')
    if value.strip()
)

ASOUD_RATE_LIMIT_ENABLED = (
    os.environ.get('ASOUD_RATE_LIMIT_ENABLED', 'true').lower() == 'true'
)
ASOUD_RATE_LIMIT_KEY_SECRET = os.environ.get('ASOUD_RATE_LIMIT_KEY_SECRET', SECRET_KEY)
ASOUD_RATE_LIMITS = {
    'pin_create': {
        'mobile': os.environ.get('ASOUD_RATE_PIN_CREATE_MOBILE', '5/hour'),
        'ip': os.environ.get('ASOUD_RATE_PIN_CREATE_IP', '20/hour'),
    },
    'pin_verify': {
        'mobile': os.environ.get('ASOUD_RATE_PIN_VERIFY_MOBILE', '20/hour'),
        'ip': os.environ.get('ASOUD_RATE_PIN_VERIFY_IP', '60/hour'),
    },
    'ws_ticket': {
        'user': os.environ.get('ASOUD_RATE_WS_TICKET_USER', '20/minute'),
    },
    'chat_member_add': {
        'user': os.environ.get('ASOUD_RATE_CHAT_MEMBER_ADD_USER', '20/hour'),
    },
    'payment_mutation': {
        'user': os.environ.get('ASOUD_RATE_PAYMENT_MUTATION_USER', '10/minute'),
    },
    'upload': {'user': os.environ.get('ASOUD_RATE_UPLOAD_USER', '60/hour')},
    'anonymous_read': {
        'ip': os.environ.get('ASOUD_RATE_ANONYMOUS_READ_IP', '120/minute'),
    },
    'authenticated_read': {
        'user': os.environ.get('ASOUD_RATE_AUTHENTICATED_READ_USER', '600/minute'),
    },
    'referral_create': {
        'user': os.environ.get('ASOUD_RATE_REFERRAL_CREATE_USER', '10/hour'),
    },
}
ASOUD_RATE_LIMIT_FAIL_CLOSED_SCOPES = (
    'pin_create',
    'pin_verify',
    'ws_ticket',
    'payment_mutation',
    'chat_member_add',
    'upload',
)
PAYMENT_SESSION_TTL_SECONDS = int(os.environ.get('PAYMENT_SESSION_TTL_SECONDS', 30 * 60))
CHAT_GROUP_MAX_PARTICIPANTS = int(os.environ.get('CHAT_GROUP_MAX_PARTICIPANTS', 100))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.users.token_authentication.ExpiringTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.core.rate_limit.AtomicRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',
        'user': '10000/hour',
        'pin_create': '5/minute',
        'pin_verify': '10/minute',
        'referral_create': '10/hour',
        'chat_member_add': '20/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Custom Exception Handler - NOW ENABLED for better error handling
    'EXCEPTION_HANDLER': 'apps.core.exception_handler.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Asoud API',
    'DESCRIPTION': 'Unified Asoud API schema',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'SWAGGER_UI_DIST': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

# (Removed duplicate LOGGING block; keeping the enhanced configuration above)

# Dictionary config
LANGUAGES = [
    ('en', _('English')),
    ('fa', _('Persian')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Configure channel layers (e.g., using Redis)
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_USERNAME = os.getenv("REDIS_USERNAME")
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')
REDIS_PORT = os.environ.get('REDIS_PORT')

# Redis URL for caching
REDIS_URL = os.environ.get('REDIS_URL')
if not REDIS_URL and REDIS_HOST:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
elif not REDIS_URL:
    REDIS_URL = "redis://localhost:6379/0"

# Django's built-in Redis cache uses the already-pinned `redis` package. Never
# silently fall back to per-process memory in production authentication flows.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'asoud',
        'TIMEOUT': 300,
    }
}
 
if REDIS_HOST:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0")],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# comments 
COMMENTS_APP = 'django_comments_xtd'
SITE_ID = 2
COMMENTS_XTD_MAX_THREAD_LEVEL = 1
COMMENTS_XTD_CONFIRM_EMAIL = False
COMMENTS_XTD_LIST_ORDER = ('-thread_id', 'order')

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://asoud.ir",
    "https://www.asoud.ir",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost",
    "http://127.0.0.1",
    "https://api.asoud.ir",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# (Removed duplicate REST_FRAMEWORK block; keeping the primary one above)
