# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('market', 'Market'), ('product', 'Product')], max_length=16)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('paid_orders', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('unique_buyers', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analytics_daily_metric',
                'ordering': ['-date', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('market_view', 'Market view'), ('add_to_cart', 'Add to cart'), ('bookmark', 'Bookmark'), ('login', 'Login'), ('logout', 'Logout'), ('paid_order', 'Paid order')], db_index=True, max_length=32)),
                ('dedupe_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('recommender', 'Recommender'), ('demand', 'Demand forecast'), ('rfm', 'RFM segmentation')], db_index=True, max_length=24)),
                ('version', models.CharField(max_length=64)),
                ('training_started_at', models.DateTimeField()),
                ('training_ended_at', models.DateTimeField()),
                ('sample_count', models.PositiveIntegerField()),
                ('validation_metrics', models.JSONField(default=dict)),
                ('artifact_path', models.CharField(max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_ml_model_artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_user_session',
                'ordering': ['-started_at'],
            },
        ),
    ]
