# Generated by Django 5.2.16 on 2026-07-13 16:49

import apps.market.upload
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Market bookmark',
                'verbose_name_plural': 'Market bookmarks',
                'db_table': 'market_bookmark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('first_mobile_number', models.CharField(max_length=15, verbose_name='First mobile number')),
                ('second_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Second mobile number')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('website_url', models.CharField(blank=True, max_length=64, null=True, verbose_name='Website url')),
                ('messenger_ids', models.JSONField(blank=True, null=True, verbose_name='Messenger IDs')),
            ],
            options={
                'verbose_name': 'Market contact',
                'verbose_name_plural': 'Market contacts',
                'db_table': 'market_contact',
            },
        ),
        migrations.CreateModel(
            name='MarketDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Percentage')),
                ('usage_count', models.PositiveBigIntegerField(default=0, verbose_name='View count')),
            ],
            options={
                'verbose_name': 'Market discount',
                'verbose_name_plural': 'Market discounts',
                'db_table': 'market_discount',
            },
        ),
        migrations.CreateModel(
            name='MarketLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Market like',
                'verbose_name_plural': 'Market likes',
                'db_table': 'market_like',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('address', models.TextField(verbose_name='Address')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip code')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Market location',
                'verbose_name_plural': 'Market locations',
                'db_table': 'market_location',
            },
        ),
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Market report',
                'verbose_name_plural': 'Market reports',
                'db_table': 'market_report',
            },
        ),
        migrations.CreateModel(
            name='MarketSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='Day of week')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
            ],
            options={
                'db_table': 'market_schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MarketSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=apps.market.upload.upload_market_slider, verbose_name='Image')),
                ('url', models.CharField(blank=True, max_length=20, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Market slider',
                'verbose_name_plural': 'Market sliders',
                'db_table': 'market_slider',
            },
        ),
        migrations.CreateModel(
            name='MarketTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('background_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('font', models.CharField(blank=True, max_length=100, null=True, verbose_name='Font')),
                ('font_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Font color')),
                ('secondary_font_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Font color')),
            ],
            options={
                'verbose_name': 'Market theme',
                'verbose_name_plural': 'Market themes',
                'db_table': 'market_theme',
            },
        ),
        migrations.CreateModel(
            name='MarketView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Market view',
                'verbose_name_plural': 'Market views',
                'db_table': 'market_view',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('company', 'Company'), ('shop', 'Shop')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queue', 'In Queue for Publication'), ('not_published', 'Not Published'), ('published', 'Published'), ('needs_editing', 'Needs Editing'), ('inactive', 'Inactive')], default='draft', max_length=20, verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Subscription start date')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Subscription end date')),
                ('business_id', models.CharField(max_length=20, verbose_name='Business id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='National code')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slogan')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to=apps.market.upload.upload_market_logo, verbose_name='Logo image')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to=apps.market.upload.upload_market_background, verbose_name='Background image')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='View count')),
                ('user_only_img', models.ImageField(blank=True, help_text='The image is not visible to the market owner.', null=True, upload_to=apps.market.upload.upload_market_userOnly, verbose_name='Image')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'db_table': 'market',
            },
        ),
    ]
