# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='marketbookmark',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='marketcontact',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketdiscount',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketlike',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='marketlocation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='marketlocation',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketreport',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='marketreport',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketschedule',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketslider',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='markettheme',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketview',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='market.market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_markets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['user', 'status'], name='idx_market_user_status'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'created_at'], name='idx_market_status_created'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['sub_category', 'status'], name='idx_market_category_status'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['business_id'], name='idx_market_business_id'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['is_paid', 'status'], name='idx_market_paid_status'),
        ),
        migrations.AlterUniqueTogether(
            name='marketbookmark',
            unique_together={('user', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='marketlike',
            unique_together={('user', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='marketschedule',
            unique_together={('market', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='marketview',
            unique_together={('user', 'market')},
        ),
    ]
