# Generated by Django 5.2.16 on 2026-08-20 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_market_status_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGatewayConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('gateway_type', models.CharField(choices=[('asoud', 'Asoud gateway'), ('personal', 'Personal gateway')], max_length=20, verbose_name='Gateway type')),
                ('user_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Personal gateway user code')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Connection status')),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_connection', to='market.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Market gateway connection',
                'verbose_name_plural': 'Market gateway connections',
                'db_table': 'market_gateway_connection',
            },
        ),
    ]
