# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='zarinpal',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zarinpal_data', to='payment.payment', verbose_name='Payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='idx_payment_user_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='idx_payment_status_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='idx_payment_user_created'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['target_content_type', 'target_id'], name='idx_payment_target'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='payment_amount_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='zarinpal',
            constraint=models.UniqueConstraint(condition=models.Q(('authority__isnull', False), models.Q(('authority', ''), _negated=True)), fields=('authority',), name='payment_zarinpal_authority_unique'),
        ),
        migrations.AddConstraint(
            model_name='zarinpal',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id',), name='payment_zarinpal_transaction_unique'),
        ),
    ]
