# Generated by Django 5.2.17 on 2026-08-31 16:59

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('national_card_front', 'National card front'), ('national_card_back', 'National card back'), ('birth_certificate', 'Birth certificate'), ('selfie_with_id', 'Selfie with identity document'), ('bank_ownership', 'Bank account ownership evidence'), ('activity_license', 'Activity license or supporting document')], default='activity_license', max_length=32),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_ownership_status',
            field=models.CharField(choices=[('unchecked', 'Unchecked'), ('possession_verified', 'Possession verified by OTP'), ('owner_matched', 'Legal owner matched'), ('owner_mismatched', 'Legal owner mismatched'), ('manual_review', 'Manual review required')], default='unchecked', max_length=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('needs_editing', 'Needs editing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.upload_identity_document, verbose_name='Market file'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iban_number',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Iban number'),
        ),
        migrations.AddConstraint(
            model_name='userdocument',
            constraint=models.UniqueConstraint(fields=('user', 'document_type'), name='unique_user_identity_document_type'),
        ),
    ]
