# Generated by Django 5.2.16 on 2026-07-13 16:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSmsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None, verbose_name='SMSTo')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('actual_cost', models.FloatField(blank=True, null=True, verbose_name='Actual_cost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('mobile_number', models.CharField(max_length=15, unique=True, verbose_name='Mobile_number')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=26, unique=True, verbose_name='Number')),
                ('estimated_cost', models.FloatField(verbose_name='EstimatedCost')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('template_id', models.IntegerField(unique=True, verbose_name='TemplateID')),
                ('content', models.TextField(verbose_name='Content')),
                ('variables', models.JSONField(help_text='Please write in Json format', verbose_name='Variables')),
                ('estimated_cost', models.FloatField(verbose_name='EstimatedCost')),
                ('is_active', models.BooleanField(default=True, verbose_name='IsActive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkSms',
            fields=[
                ('basesmsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.basesmsmodel')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='pending', max_length=12, verbose_name='Status')),
                ('message_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None, verbose_name='Message_ids')),
                ('packId', models.CharField(blank=True, max_length=64, null=True, verbose_name='PackID')),
            ],
            options={
                'verbose_name': 'BulkSms',
                'verbose_name_plural': 'BulkSms',
                'db_table': 'bulkSms',
            },
            bases=('sms.basesmsmodel',),
        ),
        migrations.CreateModel(
            name='PatternSms',
            fields=[
                ('basesmsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.basesmsmodel')),
                ('message_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Message_ids')),
            ],
            options={
                'verbose_name': 'PatternSms',
                'verbose_name_plural': 'PatternSms',
                'db_table': 'patternSms',
            },
            bases=('sms.basesmsmodel',),
        ),
    ]
