# Generated by Django 5.2.17 on 2026-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesmsmodel',
            name='to',
            field=models.JSONField(default=list, help_text='List of destination mobile numbers', verbose_name='SMSTo'),
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='message_ids',
            field=models.JSONField(blank=True, help_text='List of provider message identifiers', null=True, verbose_name='Message_ids'),
        ),
    ]
