# Generated by Django 5.2.17 on 2026-08-31 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_marketmembership_admin_approved_at_and_more'),
        ('sms', '0003_alter_basesmsmodel_to_alter_bulksms_message_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_approval', 'Waiting approval'), ('ready_for_payment', 'Ready for payment'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('partially_sent', 'Partially sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reserved_cost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('actual_cost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('provider_pack_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sms_campaign',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SmsRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('mobile_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('actual_cost', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sms_recipient',
            },
        ),
        migrations.CreateModel(
            name='SmsTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100)),
                ('persian_first_segment_chars', models.PositiveSmallIntegerField(default=70)),
                ('persian_next_segment_chars', models.PositiveSmallIntegerField(default=67)),
                ('latin_first_segment_chars', models.PositiveSmallIntegerField(default=160)),
                ('latin_next_segment_chars', models.PositiveSmallIntegerField(default=153)),
                ('price_per_segment', models.DecimalField(decimal_places=3, max_digits=14)),
                ('effective_from', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'sms_tariff',
                'ordering': ('-effective_from',),
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='has_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('phone', 'Phone'), ('excel', 'Excel'), ('manual', 'Manual')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_editing', 'Needs editing')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='template',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='template',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sms_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=15, verbose_name='Mobile_number'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TemplateID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='Please write in Json format', verbose_name='Variables'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'mobile_number'), name='unique_sms_contact_per_user'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.line'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to='market.market'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='sms.template'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms.smscampaign'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.smstariff'),
        ),
        migrations.AddConstraint(
            model_name='smsrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'mobile_number'), name='unique_sms_campaign_recipient'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['user', 'status'], name='sms_campaign_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='sms_campaign_queue_idx'),
        ),
    ]
