# Generated by Django 5.2.17 on 2026-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmembershipevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_membership_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmembershipevent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_membership_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage', verbose_name='Reply To'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='chatmessageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='chatmessageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_chat_participants', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', through='chat.ChatParticipant', through_fields=('chat_room', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat_room',
            field=models.ForeignKey(db_column='chatconversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='chat.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AddField(
            model_name='chatmembershipevent',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_events', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chat.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='chat_room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='chat.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessageread',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'status'], name='chat_conver_room_ty_e29176_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by'], name='chat_conver_created_6876e2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_f07e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['content_type', 'object_id'], name='chat_conver_content_0e6cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat_room', 'role'], name='chat_conver_chatcon_21b7bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('chat_room',), name='chat_one_owner_per_room'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'sent_at'], name='chat_messag_convers_a33ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='chat_messag_message_973666_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status'], name='chat_messag_status_8c4650_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['reply_to'], name='chat_messag_reply_t_fa2d53_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembershipevent',
            index=models.Index(fields=['chat_room', 'created_at'], name='chat_member_chat_ro_0d0d77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatanalytics',
            unique_together={('chat_room',)},
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user'], name='chat_suppor_user_id_ba6b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='chat_suppor_assigne_5b1c29_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='chat_suppor_status_5a24c9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='chat_suppor_priorit_4a4803_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='chat_suppor_categor_48562d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='chat_suppor_ticket__cc6fd1_idx'),
        ),
    ]
